# Generated by Django 5.1.1 on 2024-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainedmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='mae',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='mse',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='rmse',
            field=models.FloatField(default=0),
        ),
    ]
